spring.application.name=demo

# Database configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/poo
spring.datasource.username=postgres
# cambiar la contrasena si es diferente, deberia estar en un .env o similar, no hardcodeada, pero es solo un ejemplo.
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# cambiar a update para no borrar la base de datos. crea-drop borra es solo para testing.
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true